### ISSUE TITLE
создать аккаунт супер-админа

### ISSUE THREAD

**Issue by HushchaNatallia** [Power-Rangers-3/back-end#38]

**Comment by ValentinaBrigantina** [comment]
Ожидаем:

(только для дев режима!)

GET  /auth/superadmin 

1. создается роль SuperAdmin
2. регистрируется пользователь (email: SuperAdmin@mail.ru, password: SuperAdmin)
3. данному пользователю присваивается роль SuperAdmin
4. на фронт возвращаются данные о пользователе

**Comment by ValentinaBrigantina** [comment]
Еще раз акцентирую (для разработчиков и тестировщиков)
У нас пока костыль.
Роли SuperAdmin/Admin/User вместе с пользователем суперадмином создаются по роуту POST /superadmin, в который ничего передавать не нужно.
Далее при регистрации следующего пользователя ему автоматически присваивается базовая роль User.
Зайти в лк суперадмина: email: SuperAdmin@mail.ru, password: SuperAdmin
