### ISSUE TITLE
создать роли для пользователей сервиса

### ISSUE THREAD

**Issue by HushchaNatallia** [Power-Rangers-3/back-end#39]

**Comment by ValentinaBrigantina** [comment]
Для создания доступны роли: **SuperAdmin**/**Admin**/**User**

для тестировщика
- **POST** **/roles**  => создание новой роли, стоит ограничение на доступные значения;
-  **GET** **/role/:role** => проверка, создана ли передаваемая роль;
- **POST** **/user/role** => добавление роли пользователю, роут доступен только для пользователя с ролью SuperAdmin;

**Comment by ValentinaBrigantina** [comment]
Еще раз акцентирую (для разработчиков и тестировщиков)
У нас пока костыль.
Роли SuperAdmin/Admin/User вместе с пользователем суперадмином создаются по роуту POST /superadmin, в который ничего передавать не нужно.
Далее при регистрации следующего пользователя ему автоматически присваивается базовая роль User.
Зайти в лк суперадмина: email: [SuperAdmin@mail.ru], password: SuperAdmin
